__author__ = 'Mark'
from django import forms
from models import UserProfile

class UserProfileForm(forms.ModelForm):

    school = forms.ChoiceField(choices=[(x, x) for x in ('Abia State polytechnic',
'Abia State University, Uturu',
'ABTI-American University of Nigeria',
'Abubakar Tafawa Balewa University',
'Adamawa State polytechnic, Yola',
'Adamawa State University, Mubi',
'Adekunle Ajasin University',
'Adeniran Ogunsanya College of Education',
'Adeyemi College of Education, Ondo',
'Ahmadu Bello University',
'Ajayi Crowther University, Oyo',
'Akanu Ibiam Federal polytechnic, Unwana',
'Akwa Ibom State polytechnic',
'Allover central polytechnic, Sango-Ota Ogun State',
'Ambrose Alli University',
'Anambra State University, Anambra',
'Auchi polytechnic, Auchi',
'Bayero University, Kano',
'Bells University',
'Benson Idahosa University',
'Bowen University, Iwo',
'BStudents and exam malpracticesock University',
'Cetep City University, Lagos',
'College of Education, Afaha-Nsit',
'College of Education, Agbor',
'College of Education, Akwanga',
'College of Education, Azare',
'College of Education, Ekiadolor',
'College of Education, Gindiri',
'College of Education, Ikere Ekiti',
'College of Education, Katsina Ala',
'College of Education, Katsina-Ala',
'College of Education, Oro, Kwara State',
'College of Education, Warri',
'College of Education, Zuba',
'Covenant University',
'Crawford University,Oye Ekiti',
'Cross River University of Technology',
'Delta state polytechnic, Ozoro',
'Delta State University, Abraka',
'Dorben polytechnic (formerly Abuja School of Accountancy and Computer Studies)',
'Ebonyi State University',
'Enugu State University of Science & Technology',
'FCT College of Education, Zuba',
'Federal coll. of Animal health & production Tech., Ibadan',
'Federal College of Education (Special), Oyo',
'Federal College of Education (Technical) Gombe',
'Federal College of Education (Technical) Gusau',
'Federal College of Education, (Technical) Bich',
'Federal College of Education, Akoka',
'Federal College of Education, Obudu',
'Federal College of Education, Okene',
'Federal College of Education, Omoku',
'Federal College of Education, pankshin',
'Federal College of Education, Yola',
'Federal College of Education, Zaira',
'Federal College of Education, Zaria',
'Federal polytechnic Bida',
'Federal polytechnic Offa',
'Federal polytechnic, Ado Ekiti',
'Federal polytechnic, Bauchi,'
'Federal polytechnic, Birnin-Kebbi',
'Federal polytechnic, Damaturu,'
'Federal polytechnic, Ede',
'Federal polytechnic, Idah',
'Federal polytechnic, Ilaro',
'Federal polytechnic, Mubi',
'Federal polytechnic, Nassarawa',
'Federal polytechnic, Nekede',
'Federal polytechnic, Oko',
'Federal University of Technology, Minna',
'Federal University of Technology, Owerri',
'Federal University Of Technology, Yola',
'Federal University of Technology,Akure',
'Gateway polytechnic Saapade',
'Gombe state University',
'Hussaini Adamu Federal polytechnic, kazaure',
'Igbinedion University',
'Imo State University',
'Institute of Management Technology, Enugu',
'Joseph Ayo Babalola University',
'Kaduna polytechnic',
'Kano State College of Education, Kano',
'Kano State polytechnic, Kano',
'Katsina State University',
'Kogi State University',
'Kwara State College of Education',
'Kwara State polytechnic',
'Ladoke Akintola University of Tech.',
'Lagos City Computer College',
'Lagos City polytechnic',
'Lagos State polytechnic',
'Lagos State University',
'Lead City University',
'Maritime Academy of Nigeria, Oron',
'Michael Okpara University',
'Moshood Abiola polytechnic, Abeokuta',
'Nasarrawa State University',
'National Open University',
'National Teachers Institute, kaduna',
'Niger Delta University',
'Niger State polytechnic, Zungeru',
'Nigerian Coll. of Aviation Tech., Zaira',
'Nigerian Defence Academy',
'Nnamdi Azikiwe University of Agriculture, Umudike',
'Nuhu Bamalli polytechnic, Zaria, Kaduna State',
'Nwafor Orizu College of Education',
'Obafemi Awolowo University, ile-ife',
'Olabisi Onabanjo University, Ago-Iwoye',
'Osun State College of Education, Ila-Orangun',
'Osun State College of Education, Ilesa',
'Osun State College of Technology, Esa-Oke',
'Osun State polytechnic, Iree',
'Osun State University',
'Oyo State College Of Education, Oyo',
'pan African University, Lekki',
'plateau State University',
'Ramat polytechnic, Maiduguri',
"Redeemer's University",
'Renaissance University, Enugu',
'River State polytechnic, Bori',
'Rivers State College of Education',
'Rivers State University of Science and Technology',
'Rufus Giwa polytechnic, Owo',
'Salem University, Lokoja',
'Shaka polytechnic',
"St. paul's University College, Awka",
'Tai Solarin University of Education, Ijebu-Ode',
'The polytechnic, Ibadan',
'Theological College of Northern Nigeria,Bukuru',
'University of Abuja',
'University of Ado-Ekiti',
'University of Agriculture, Abeokuta',
'University of Benin',
'University of Calabar',
'University of Education, Ikere-Ekiti',
'University of Ibadan',
'University of Ilorin',
'University of Jos',
'University of Lagos',
'University of Maiduguri',
'University of Mkar, Mkar',
'University of Nigeria',
'University of port-harcourt',
'University of Technology, Akwa-Ibom',
'University Of Uyo',
'Usmanu Danfodiyo University, Sokoto',
'Wesley University, Ondo',
'Yaba College of Tech.',
)])
    class Meta:
        model = UserProfile
        fields = ('phone', 'school')

